// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nncpapnlnrtssbruzkla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uY3BhcG5sbnJ0c3NicnV6a2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTYwMzMsImV4cCI6MjA2NTMzMjAzM30.OWgFgAF_J6vSZae6rvCGjb_ATMnlq0MIFNQfBEJoiao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);